server:
  port: 8000

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    initialization-mode: always
    platform: h2
    data: classpath:schema.sql, classpath:data.sql
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
      driver-class-name: org.h2.Driver
      username: vivian
      password: abcd1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace



